version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: uofa/s2i-shepherd-drupal-dev
    # Chrome webdriver requires this - used for tests.
    privileged: true
    hostname: ${PROJECT}
    environment:
      SITE_TITLE: WCMS D8
      SITE_MAIL: site@example.com
      SITE_ADMIN_EMAIL: admin@example.com
      SITE_ADMIN_USERNAME: admin
      SITE_ADMIN_PASSWORD: password
      PUBLIC_DIR: /shared/public
      HASH_SALT: random-hash
      CONFIG_SYNC_DIRECTORY: /shared/private/random-hash/sync
      SHEPHERD_SITE_ID: 2
      SHEPHERD_URL: http://shepherd.test
      SHEPHERD_TOKEN: super-secret-token
      SHEPHERD_INSTALL_PROFILE: ua
      DATABASE_HOST: db
      REDIS_HOST: redis
      MEMCACHE_ENABLED: 1
      MEMCACHE_HOST: memcache
      SHEPHERD_SECRET_PATH: /code/private
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: serverName=${PROJECT}.${DOMAIN}
      VIRTUAL_HOST: ${PROJECT}.${DOMAIN}
      # Do not define this as '/' or apache2 will give strange behaviour
      # WEB_PATH: /
    volumes:
      - .:/code
      - ./shared:/shared
      - ${XDG_RUNTIME_DIR}/keyring:/ssh
    networks:
      - default

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password
    networks:
      - default

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: mail.${PROJECT}.${DOMAIN}
    networks:
      - default

  redis:
    image: redis:alpine
    networks:
      - default

  memcached:
    image: jboss/infinispan-server:9.4.11.Final
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - standalone-memcached.xml
    volumes:
      - ./standalone-memcached.xml:/opt/jboss/infinispan-server/standalone/configuration/standalone-memcached.xml
    networks:
      - default
